[profile.default]
src = 'src'
test = 'test'
script = 'script'
out = 'out'
libs = ['lib']
cache_path = 'cache'
solc = "0.8.30"
via_ir = true
optimizer = true
optimizer_runs = 200

# For dependencies
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@filecoin-pay/=lib/filecoin-pay/src/',
]

# Allow reading test data files
fs_permissions = [{ access = "read", path = "./test" }]
